name: Keycollector
env:
  PACKAGE_NAME: "flask-ci-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VAR: "This is job level"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check variables
        run: |
          echo "Hello Message one"
          echo "PACKAGE_NAME = ${{ env.PACKAGE_NAME }}"

      - name: List current folder
        run: ls -la

      - name: Show Env var
        run: |
          echo "VAR: ${{ env.VAR }}"
          echo "SUPERLOCAL: $SUPER_LOCAL"
        env:
          SUPER_LOCAL: "SUPERLOCAL VAR"
