name: Keycollector
env:
  PACKAGE_NAME: "flask-ci-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VAR: "This is job level"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check variables
        run: |
          echo "Hello Message one"
          echo "PACKAGE_NAME = ${{ env.PACKAGE_NAME }}"

      - name: List current folder
        run: ls -la

      - name: Show Env var
        run: |
          echo "VAR: ${{ env.VAR }}"
          echo "SUPERLOCAL: $SUPER_LOCAL"
        env:
          SUPER_LOCAL: "SUPERLOCAL VAR"

      - name: show secrets IP
        run: echo "${{ secrets.SERVER_IP }}"

      - name: ssh setup
        run: |
             mkdir -p ~/.ssh
             echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
             chmod 600 ~/.ssh/id_rsa
             ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: ssh and list files
        run: ssh -i ~/.ssh/id_rsa rick@${{ secrets.SERVER_IP }} "ls -la /home/rick"

      - name: upload secret to .env
        env:
          SECRET_VARIABLE: ${{ secrets.SECRET_VARIABLE }}
        run: |
          ssh -i ~/.ssh/id_rsa rick@${{ secrets.SERVER_IP }} "\
            echo \"SECRET_VARIABLE=$SECRET_VARIABLE\" >> /home/rick/projects/keycollector/.env"

      - name: show the env
        run: ssh -i ~/.ssh/id_rsa rick@${{ secrets.SERVER_IP }} "ls -la /home/rick/projects/keycollector/.env"
