name: Keycollector

on:
  push:
    branches:
       - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show secret phrase
      run: echo "Secret is: $ITS_SECRET_PHRASE"
      env:
        ITS_SECRET_PHRASE: ${{ secrets.ITS_SECRET_PHRASE }}

    - name: Add phrase to .env
      run: |
        ssh rick@${{ secrets.IP }} <<EOF
        echo "SECRET_VARIABLE=${{ secrets.ITS_SECRET_PHRASE }}" >> /home/rick/projects/keycollector/.env
        EOF
      env:
        ITS_SECRET_PHRASE: ${{ secrets.ITS_SECRET_PHRASE }}
      
